numpy/numtype

src/numpy-stubs/_numtype.pyi

... so that I can check whether mypy actually uses the `numtype` stubs, and not the `numpy` ones <sub>because I haven't been able to figure out how to do that yet...</sub>

⚗️ hallucinate `numpy._numtype` into existence (for debugging)

---

pyproject.toml
test/pyproject.toml
test/uv.lock
uv.lock

https://github.com/DetachHead/basedpyright/releases/tag/v1.26.0

⬆️ bump `basedpyright` to `1.26.0`

---

.vscode/settings.json
pyproject.toml
test/README.md
test/main.py
test/pyproject.toml

... and some other mypy-related project structure tweaks

🔧 allow running `numtype-test` with `uv run --project`

---

.pre-commit-config.yaml

🔧 pre-commit support

---

src/numpy-stubs/testing/print_coercion_tables.pyi

🏷️ stub `numpy.testing.print_coercion_tables`

---

.github/workflows/ci.yml
.vscode/settings.json
pyproject.toml
src/numpy-stubs/_core/multiarray.pyi
test/README.md
test/mypy.py
test/static/accept/ndarray_conversion.pyi
uv.lock

... until the next basedmypy is released

🔨 use `mypy 1.15.0` (for the time being)

---

.github/workflows/ci.yml
src/numpy-stubs/__init__.pyi
src/numpy-stubs/_globals.pyi

🏷️ stub `numpy._globals`

---

src/numpy-stubs/__init__.pyi
src/numpy-stubs/_expired_attrs_2_0.pyi

🏷️ stub `numpy._expired_attrs_2_0`

---

src/numpy-stubs/lib/_iotools.pyi

🏷️ stub `numpy.lib._iotools`

---

src/numpy-stubs/lib/introspect.pyi

🏷️ stub `lib.introspect`

---

pyproject.toml
src/numpy-stubs/ruff.toml
src/numtype/__init__.py
src/numtype/ruff.toml
src/numtype/version.py
test/runtime/test_numtype.py

it currently only re-exports the `numpy.typing` type-aliases

📦 new public `numtype` package

---

.github/workflows/ci.yml
src/numpy-stubs/_core/records.pyi
test/static/accept/rec.pyi
test/static/reject/rec.pyi

re-exported as `numpy.rec`
towards #98

🐛 fix typing errors in `_core.records`

---

src/numpy-stubs/_typing/_char_codes.pyi
test/static/accept/ctypeslib.pyi

this assumes modern system (no 16bit cpu), and supported "regular" C compiler, which should be the case for for >99% of the users

♻️ re-organize the dtype character code literal types

---

.github/workflows/ci.yml
src/numpy-stubs/__init__.pyi
src/numpy-stubs/_core/getlimits.pyi
test/static/accept/getlimits.pyi

The `iinfo` and `finfo` constructors now support all relevant dtype char-codes and names
---
towards ##98

🐛✨ fix and improve `numpy.{f,i}info` in `_core.getlimits`

---

src/numpy-stubs/__init__.pyi
src/numpy-stubs/_core/memmap.pyi
test/static/accept/memmap.pyi

🐛 fix `memmap` in `numpy._core.memmap`

---

.github/workflows/ci.yml
pyproject.toml
src/_numtype/__init__.pyi
src/_numtype/ruff.toml
test/runtime/test_numtype.py
test/static/accept/comparisons.pyi
test/static/ruff.toml
test/static/test__numtype.pyi

... with `optype`an shape-typed type aliases for  scalar- and array-likes, of both the "coercible" (`To*`) and the `optype.Just` (`As*`) kinds.
Once proper testing is in place, and we've decided upon a naming scheme, then these will probably be moved to the `numtype` namespace, making them part of the public API.

📦 new private type-check-only `_numtype` package

---

src/_numtype/__init__.pyi

will be private and type-check-only for now

✨ `_numtype`: new `NDim(0|1|2|3)?`, `M?Array(0|1|2|3)?`, and `Matrix` aliases

---

src/_numtype/__init__.pyi
test/static/test__numtype.pyi

The `*_nd` aliases now also accept `np.generic` scalar types. If those should be rejected, `*_1nd` can be used instead.

✨ `_numtype`: `*_{1,2,3}nd` array-like aliases with minimum ndim

---

.github/workflows/ci.yml
src/numpy-stubs/_typing/_char_codes.pyi
src/numpy-stubs/ctypeslib/__init__.pyi
src/numpy-stubs/ctypeslib/_ctypeslib.pyi
test/static/accept/ctypeslib.pyi

closes #99
---
This mostly ignores "overlapping overload" errors, and doesn't include (many) fixes. These ignores are a temporary measure that won't be needed anymore once the integer scalar types have been made concrete (see #136). So backporting this upstream isn't really needed.
Quick side-note: Annotating the Python 3.14 complex ctypes is going to have to wait until numpy/numpy#28360 is fixed.

🐛 fix typing errors in `numpy.ctypeslib`

---

src/numpy-stubs/lib/_arrayterator_impl.pyi

🐛 fix typing errors in `numpy.lib._arrayterator_impl`

---

src/numpy-stubs/lib/_index_tricks_impl.pyi
test/static/accept/index_tricks.pyi

🐛 fix typing errors in `numpy.lib._index_tricks_impl`

---

src/numpy-stubs/__init__.pyi
src/numpy-stubs/lib/_index_tricks_impl.pyi
test/static/accept/index_tricks.pyi

This also moves `ndenumerate` and `ndindex` from `__init__.pyi` to  `lib/_index_tricks_impl.pyi` in `numpy-stubs`.
---
closes #190

🐛 fix typing errors in `ndenumerate`

---

.github/workflows/ci.yml
.pre-commit-config.yaml

Additionally, all pre-commit hooks will now be ran from the CI, including `ruff check` and `ruff format`

👷 `add-trailing-comma` pre-commit hook and CI step

---

.github/workflows/ci.yml
pyproject.toml
uv.lock

the goal is to speed up the CI runs

👷 split CI steps into (parallelizable) jobs

---

.mypyignore-todo
src/numpy-stubs/__init__.pyi
src/numpy-stubs/lib/_shape_base_impl.pyi
src/numpy-stubs/matlib.pyi

🏷️ 🗑️ annotate the missing deprecated `row_stack` function

---

.mypyignore
.mypyignore-todo
src/numpy-stubs/_core/overrides.pyi
src/numpy-stubs/core/__init__.pyi
src/numpy-stubs/core/overrides.pyi

🏷️ stub `numpy._core.overrides`

---

.mypyignore-todo
src/numpy-stubs/__init__.pyi

the following methods were missing according to stubtest:
- `numpy.object_.__call__` 
- `numpy.timedelta64.__class_getitem__`

🏷️ fix stubtest errors in `timedelta64` and `object_`

---

.mypyignore
.mypyignore-todo
src/numpy-stubs/__init__.pyi
src/numpy-stubs/dtypes.pyi

`numpy.dtype.type` is `None` as class attribute, and `type[SCT]` as instance attribute. This can't be expressed in the typing system, so it's kept as `@property`, and added to the permanent `.mypyignore`.

🏷️ fix stubtest errors in `numpy.dtype` and `numpy.dtypes.*`

---

.mypyignore-todo
src/numpy-stubs/lib/_function_base_impl.pyi
src/numpy-stubs/ma/extras.pyi
test/static/reject/lib_function_base.pyi

This fixes the signatures of the following public `numpy` members:
- `average`
- `ma.average`
- `median`
- `corrcoef`

🏷️ fix stubtest errors in `numpy.lib._function_base_impl`

---

.mypyignore-todo
src/numpy-stubs/_core/_type_aliases.pyi

all stubtest errors were caused by namespace pollution, so this is more of a workaround to please stubtest than something that's actually useful

🏷️ fix stubtest errors in `numpy._core._type_aliases`

---

tool/stubtest.py

cc @jorenham 
I was looking into https://github.com/python/mypy/pull/18756#issuecomment-2702314731
It looks like the pre-release version of mypy crashes (for some reason related to property changes, will investigate). Crash logs are emitted to stderr and process exits with exit code 2.
This code does correctly chain the exit code, but swallows stderr.

Don't swallow stderr output

---

src/numpy-stubs/_core/_multiarray_umath.pyi

🩹 fix `numpy.inner` overload

---

src/numpy-stubs/ma/testutils.pyi
src/numpy-stubs/testing/__init__.pyi
test/static/accept/testing.pyi
tool/.mypyignore.txt

this also applies the `unittest.TestCase` workaround from #280 (applied in #281) to `numpy.testing.TestCase`
cc @guan404ming

🤡 also apply the `unittest.TestCase` workaround to `numpy.testing.TestCase`

---

test/generate_emath.py
test/generate_scalar_binops.py

pyright causes `isinstance(x, np.generic)`  to be narrowed to `generic[Unknown]`, which snowballs into many `reportUnknownMemberType` and `reportUnknownArgumentType`, unless explicitly casted (even though mypy flags it as `redundant-cast`)

🚨 fix pyright backcompat issues

---

pyproject.toml
uv.lock

https://github.com/astral-sh/ruff/releases/tag/0.10.0

⬆️ bump `ruff` to `0.10.0`

---

pyproject.toml
tool/ruff.toml
tool/ufunc.py
tool/ufunc.py.lock
uv.lock

The ufuncs that support string-like input never seem to include those signatures in their `ufunc.types`. This script automatically figures these out. It  can only list the aggregates input/output types (including the string-like ones) at the moment. But it could easily be extended to display more information about e.g. a specific ufunc signature. It could perhaps even be turned into an automatic ufunc signature code generator, or "just" an exhaustive type-test generator for ufuncs.
This script has been used to generate the following overview (respost from https://github.com/numpy/numtype/issues/230#issuecomment-2734958282):
---
This includes the supported `SUVT` signatures that, for some reason, are never listed in `ufunc.types`.
This only includes the *overridable* (through …

🔨 ufunc signature introspection script

---

pyproject.toml
uv.lock

https://github.com/DetachHead/basedpyright/releases/tag/v1.28.2

⬆️ bump `basedpyright` to `1.28.2` (`pyright 1.1.397`)

---

src/_numtype/__init__.pyi
src/numpy-stubs/_core/getlimits.pyi

This broadens the `c[longdouble]` aliases so that they also accepts 96-bit dtypes. This also ensures that `_numtype` will still work after #136.

✨ more `_numtype` abstract scalar type aliases

---

test/static/accept/fft.pyi

Fixes typo in static tests for fft, in which `rfftfreq` was left untested and `fftfreq` was tested twice.
I was unable to run the mypy test, but the basedpyright test is still happy.

Changed duplicated fftfreq tests to rfftfreq.

---

test/generated/emath.pyi
tool/testgen.py

- fixed non-deterministic union ordering in the `emath` tests
- don't overwrite existing tests if unchanged
- print unified diffs of regenerated tests to stdout

🤖 improved test generation script

---

src/numpy-stubs/__init__.pyi

follow-up of #359
This change somehow didn't break anything, which is a good sign <sub>hopefully</sub>

🐛 change `[u]intp` to be statically distinguishable from `int64` and `longlong`

---

src/numpy-stubs/_core/umath.pyi
test/static/accept/ufuncs.pyi
test/static/reject/ufuncs.pyi

🏷️ ufunc annotations for `spacing`

---

.vscode/settings.json

closes #374
---
It is enabled by default, which causes false positives about incorrect schema definitions in `pyproject.toml`. I already had it globally disabled, but for it helps with DX to disable it in the project's vscode config as well.
cc @guan404ming

🧑‍💻 don't use schema's in the even-better-toml vscode plugin

---

pyproject.toml
tool/stubtest.py.lock
tool/ufunc.py.lock
uv.lock

https://github.com/DetachHead/basedpyright/releases/tag/v1.28.4

⬆️ bump `baseedpyright` to `1.28.4` (pyright `1.1.398`)

---

src/numpy-stubs/_core/umath.pyi

🏷️ stub _-{l,r}]strip_chars

---

test/runtime/test_format_ignores.py
tool/__init__.py
tool/test/__init__.py
tool/test/test_format_ignores.py

`format_ignores` is used in CI and lefthook but it's lack of some test, which is kind of unstable and dangerous when modifying this func.
Thus, I write some unit test and integration test for it~

✅ add tests for `format_ignores`

---

.github/workflows/ci.yml
.vscode/settings.json
pyproject.toml
tool/stubtest.py.lock
tool/ufunc.py.lock
uv.lock

This way we avoid installing unnecessary development dependencies in the CI steps.
The `docs` group is now also installed as a default development dependency.

📦 reoganize development dependency groups

---

CONTRIBUTING.md

ref: https://github.com/numpy/numtype/pull/431#issuecomment-2764154100

📝 add instructions for previewing documentation site

---

.github/dependabot.yml

Close #426 
Ref: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#allow--

👷 update dependabot configuration to allow all dependency types

---

uv.lock

Action become green check but still can't update packages
https://github.com/guan404ming/numtype/actions/runs/14199861094/job/39783918594

⬆️ bump `griffe` to `1.7.2` and `mkdocs-material` to `9.6.11`

---

lefthook.yml

make the doc build be in the `lefthook` ensuring the build works normal in local

👷 add docs-check to `lefthook`

---

src/_numtype/@test/test_to_array.pyi
src/numpy-stubs/@test/static/accept/array_constructors.pyi
src/numpy-stubs/@test/static/accept/multiarray.pyi
src/numpy-stubs/@test/static/accept/twodim_base.pyi
src/numpy-stubs/__init__.pyi
src/numpy-stubs/_core/records.pyi
src/numpy-stubs/_core/shape_base.pyi
src/numpy-stubs/lib/_arraypad_impl.pyi
src/numpy-stubs/lib/_stride_tricks_impl.pyi

ref: https://github.com/numpy/numtype/pull/474#discussion_r2031689849

♻️ refactor type variable names from `_SCT` to `_ScalarT`

---

src/numpy-stubs/@test/generated/ndarray_ops_add.pyi
tool/testgen.py

closes #488
towards #491
---
All of the newly generated tests pass without having to change the stubs 😎

🤖 `ndarray` binop testgen with abstract scalar types

---

pyproject.toml
uv.lock

https://github.com/astral-sh/ruff/releases/tag/0.11.8

⬆️ bump `ruff` to `0.11.8`

---

src/_numtype/@test/test_rank.pyi
src/_numtype/_rank.pyi

This adds several new type-check-only types to `_numtype`, which can be divided into two categories: Rank-types, and broadcast type-aliases.
The rank-types subclass and wrap the integer tuples that are currently used as shape-types. This makes them backwards-compatible (after modifying `ndarray.shape`), while making it possible to embed static-typing information, such as the broadcasting rules, into these types, as type-check-only methods or attributes. 
- `Rank0 <: ()`
- `Rank1 <: (int,)`
- `Rank2 <: (int, int)`
- `Rank3 <: (int, int, int)`
- `Rank4 <: (int, int, int, int)`
- `Rank0ToN <: (int, ...)` 
- `Rank1ToN <: (int, *(int, ...))` 
- `Rank2ToN <: (int, int, *(int, ...))`
- `Rank3ToN <: (int, int, int, *(int, ...))`
- `Rank4ToN <: (int, int, int, int, *(int, ...))`
Another advantage …

✨ towards a broadcasting-aware rank-typing framwork

---

pyproject.toml

the `orjson` dev group has been removed a while back, and was causing the `mypy` task to fail

💚 fix tox config

---

tool/stubtest.py
tool/unstub.py

As workaround for python/mypy#18997

🔨 only delete `__init__.pyi` when "unstubbing"

---

pyproject.toml
src/numpy-stubs/@test/static/accept/testing.pyi
src/numpy-stubs/__init__.pyi
src/numpy-stubs/ma/core.pyi
src/numpy-stubs/matrixlib/defmatrix.pyi
src/numpy-stubs/testing/_private/utils.pyi
tool/allowlists/common.txt
tool/allowlists/path-py311.txt
tool/allowlists/path-py312.txt
tool/stubtest.py
tool/stubtest.py.lock
tool/ufunc.py.lock
uv.lock

https://mypy.readthedocs.io/en/stable/changelog.html#mypy-1-16

⬆️ bump `mypy` to `1.16.0`

---

pyproject.toml
src/_numtype/__init__.py

📦 `uv` build backend

---

src/numpy-stubs/__init__.pyi
src/numpy-stubs/_core/_multiarray_umath.pyi
src/numpy-stubs/_core/fromnumeric.pyi
src/numpy-stubs/_core/overrides.pyi
src/numpy-stubs/lib/_iotools.pyi

This ports the following upstream changes:
- numpy/numpy#29170
- numpy/numpy#29171
- numpy/numpy#29176
- numpy/numpy#29177
- numpy/numpy#29184
Closes #581

👽️ Port the recent _core and lib numpy typing PRs
