numpy/numtype

src/numpy-stubs/testing/_private/extbuild.pyi
=> 🏷️ stub `numpy.testing._private`

src/numpy-stubs/_core/arrayprint.pyi, test/static/reject/arrayprint.pyi
includes https://github.com/numpy/numpy/pull/28270
=> ✨🐛 fix and improve `numpy._core.arrayprint`

src/numpy-stubs/lib/recfunctions.pyi, test/runtime/accept/recfunctions.py, test/runtime/ruff.toml, test/static/reject/modules.pyi
=> 🏷️ stub `lib.recfunctions` and test it

pyproject.toml, uv.lock
https://github.com/DetachHead/basedpyright/releases/tag/v1.27.0
=> ⬆️ bump `basedpyright` to `1.27.0`

src/numpy-stubs/_core/shape_base.pyi, test/static/accept/array_constructors.pyi
=> 🐛 fix typing errors in `_core.shape_base`

.github/workflows/ci.yml, src/numpy-stubs/_array_api_info.pyi, test/static/accept/array_api_info.pyi
=> 🐛 fix typing errors in `__array_api_info__`

src/numpy-stubs/_core/fromnumeric.pyi, test/static/accept/fromnumeric.pyi, test/static/reject/fromnumeric.pyi
=> 🐛✨ fix and improve `_core.fromnumeric`

.github/workflows/ci.yml, src/numpy-stubs/__init__.pyi, src/numpy-stubs/_core/numeric.pyi, test/static/accept/numeric.pyi
=> 🐛 fix typing errors in `numpy._core.numeric`

.github/workflows/ci.yml, src/numpy-stubs/lib/_arraysetops_impl.pyi, test/static/accept/arraysetops.pyi
=> 🐛✨ fix and improve `numpy.lib._arraysetops_impl`

src/numpy-stubs/lib/_version.pyi
=> 🐛 fix typing errors in `numpy.lib._version`

src/numpy-stubs/lib/_ufunclike_impl.pyi, test/static/accept/ufunclike.pyi
=> 🐛✨ fix and improve `numpy.lib._ufunclike_impl`

src/numpy-stubs/lib/_type_check_impl.pyi, test/static/accept/type_check.pyi
=> 🐛✨ fix and improve `numpy.lib._type_check_impl`

src/numpy-stubs/lib/_twodim_base_impl.pyi, test/static/accept/twodim_base.pyi
=> 🐛 fix typing errors in `numpy.lib._twodim_base_impl`

src/numpy-stubs/lib/_shape_base_impl.pyi
=> 🐛 fix typing errors in `numpy.lib._shape_base_impl`

.github/workflows/ci.yml, src/numpy-stubs/lib/_function_base_impl.pyi, src/numpy-stubs/lib/_histograms_impl.pyi, test/static/accept/lib_function_base.pyi, test/static/reject/lib_function_base.pyi
=> 🐛✨ fix and improve `numpy.lib._function_base_impl`

src/numpy-stubs/_core/_type_aliases.pyi
=> 🏷️ annotate the accidental exports in `numpy._core._type_aliases`

.github/workflows/ci.yml, src/numpy-stubs/ma/extras.pyi, src/numpy-stubs/ma/mrecords.pyi
=> 🐛 fix remaining typing errors in `numpy.ma`

.mypyignore-todo, src/numpy-stubs/lib/_twodim_base_impl.pyi, test/static/accept/twodim_base.pyi
only the parameter name fix should be backported
=> 🏷️ fix stubtest errors in `numpy.lib._twodim_base_impl`

test/runtime/accept/shape.py
=> 🏷️  add acceptance tests for 2D arrays

src/numpy-stubs/random/_pickle.pyi
=> 🏷️ stub numpy.random._pickle

src/numpy-stubs/ma/testutils.pyi, tool/.mypyignore-todo.txt, tool/.mypyignore.txt
=> 🏷️ stub `numpy.ma.testutils`

src/_numtype/__init__.pyi, src/numpy-stubs/lib/_function_base_impl.pyi, test/static/accept/lib_function_base.pyi, test/static/reject/lib_function_base.pyi
This also adds `_numtype.Array_4d`.
---
closes #292
=> 👽️ ✨ `numpy.meshgrid`: port numpy/numpy#28462 and add shape-typing 

.github/workflows/ci.yml, tool/allowlists/path-py311.txt, tool/allowlists/path-py312.txt, tool/stubtest.py
=> 👷 stubtest on Windows in CI

.github/PULL_REQUEST_TEMPLATE.md
=> 📚 add pull request templates

src/numpy-stubs/_typing/_ufunc.pyi, test/static/accept/char.pyi, test/static/accept/strings.pyi, test/static/reject/char.pyi, test/static/reject/strings.pyi
=> ♻️ tighten `_Call21Bool` dtype

.vscode/extensions.json
=> 🧑‍💻 add `seatonjiang.gitmoji-vscode` in `extensions.json`

tool/README.md
=> 📝 add tools doc

src/numpy-stubs/_core/umath.pyi, test/static/accept/ufuncs.pyi, test/static/reject/ufuncs.pyi
=> 🏷️ stub `signbit`

src/numpy-stubs/_core/numeric.pyi
=> 🐛 implicit export for normalize_axis_tuple

src/numpy-stubs/_core/umath.pyi
=> ♻️ refactor `_ArrayT | tuple` to `out1`

src/numpy-stubs/_core/umath.pyi
ref: https://github.com/numpy/numtype/pull/376#discussion_r2008970747
=> 🐛 fix fallback in `_Call21Bool`

lefthook.yml, pyproject.toml, uv.lock
=> 🧑‍💻 add `lefthook` for pre-commit formatting and linting

src/numpy-stubs/_core/defchararray.pyi, src/numpy-stubs/dtypes.pyi, test/static/reject/flatiter.pyi, test/static/reject/lib_polynomial.pyi, test/static/reject/ndarray.pyi, test/static/reject/ndarray_misc.pyi, tool/README.md, tool/format_ignores.py
=> 🧑‍💻 add `format_ignores` tool

.github/workflows/ci.yml
=> 👷  add `format-ignores` step to CI

CONTRIBUTING.md, pyproject.toml
=> 📝 NumType-specific contributing guide

src/numpy-stubs/_core/umath.pyi
=> 🏷️ stub _core.umath._[{l,r}]strip_whitespace

tool/format_ignores.py
=> 🐛 update `format_ignores.py` to accept multiple paths as input

mkdocs.yml
this adds a cookie consent banner (sorry), and bundles external assets for self-hosting
=> 📝 ensure data privacy on the docs site

docs/index.md, docs/style/theme.css, docs/user_guide.md, docs/user_guide/differences.md, docs/user_guide/index.md, mkdocs.yml, pyproject.toml, uv.lock
=> 📝 document some of the differences with NumPy 

CONTRIBUTING.md
Tiny thing, but my brain wouldn’t let it go. 🧑‍💻
=> 📝 update reference link order

src/numpy-stubs/__init__.pyi, src/numpy-stubs/_typing/_nbit_base.pyi
=> 🗑️ mark `NBitBase` as deprecated in type stubs

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/publish-pypi.yml
Reverts numpy/numtype#438
this was fake news apparently: https://github.com/astral-sh/setup-uv/issues/356
=> Revert "⬆️ Bump astral-sh/setup-uv from 5 to 6"

lefthook.yml
#432 broke lefthook
this fixes it
=> 💚 fix lefthook `uv run` commands

docs/.nav.yml, mkdocs.yml, pyproject.toml, uv.lock
https://github.com/lukasgeiter/mkdocs-awesome-nav
=> ➕ 📝 simlify docs navigation specification with `mkdocs-awesome-nav`

.github/workflows/docs.yml
it seems it would run every time push to main
=> 👷 only trigger deploy on changes to docs

docs/overrides/main.html, mkdocs.yml
=> 📈 documentation analytics

.github/labeler.yml
=> 👷 add `labeler`

docs/style/color.css, docs/style/font.css, docs/style/overrides.css, docs/style/theme.css, mkdocs.yml
=> 💄 make the docs look more like pydata-sphinx-theme

src/_numtype/__init__.pyi, src/_numtype/_dtype.pyi, src/numpy-stubs/@test/static/accept/dtype.pyi, src/numpy-stubs/__init__.pyi, src/numpy-stubs/_typing/_char_codes.pyi
=> ✨ `_numtype` dtype-like type-aliases

tool/testgen.py
towards #489
---
This produces 100 failing tests (for `ndarray.__add__`) at the moment, which I'll address in a follow-up.
=> 🤖 testgen `ndarray` binop vs builtin scalar types

src/numpy-stubs/@test/generated/ndarray_divmod.pyi, src/numpy-stubs/__init__.pyi, tool/testgen.py
=> ✅ fix failing `ndarray.__divmod__` tests

README.md
in the correct branch this time...
=> 📝 fix numtype logo url

src/numpy-stubs/@test/static/accept/lib_function_base.pyi, src/numpy-stubs/lib/_function_base_impl.pyi
=> ✨ improved `cov` and `corrcoef` annotations

src/_numtype/@test/test_rank.pyi, src/_numtype/__init__.pyi, src/_numtype/_rank.pyi, src/_numtype/_shape.pyi, src/numpy-stubs/@test/static/accept/linalg.pyi, src/numpy-stubs/@test/static/accept/scalars.pyi, src/numpy-stubs/__init__.pyi, src/numpy-stubs/_core/_multiarray_umath.pyi, src/numpy-stubs/_core/shape_base.pyi, src/numpy-stubs/linalg/_linalg.pyi
=> ♻️ cleaner rank types & better naming

pyproject.toml
see https://learn.scientific-python.org/development/guides/packaging-compiled/#license
=> 📄 remove license trove classifier

.github/workflows/ci.yml, pyproject.toml
=> ✨ Python 3.14 support

.github/dependabot.yml
for `uv` it was reporting
```
Dependabot encountered '1' error(s) during execution, please check the logs for more details.
+---------------------------------------------------------------------+
|                               Errors                                |
+---------------------------+-----------------------------------------+
| Type                      | Details                                 |
+---------------------------+-----------------------------------------+
| dependency_file_not_found | {                                       |
|                           |   "message": "No files found in /tool", |
|                           |   "file-path": null                     |
|                           | }                                       | …
```
=> 💚 fix dependabot config

.github/workflows/docs.yml, .github/workflows/publish-pypi.yml
towards [SPEC 5](https://scientific-python.org/specs/spec-0005/)
=> 📌 pin semver tags of github actions actions

.github/renovate.json5, .github/workflows/renovate.yml
=> 🔧 renovate config tweaks

.github/renovate.json5
=> 🔧 configure the repository that renovate should use
